CREATE TABLE LOCATIONS (
    LOCATION_ID NUMBER(5) PRIMARY KEY,
    DISTRICT    VARCHAR2(50) NOT NULL,
    SECTOR      VARCHAR2(50) NOT NULL,
    ZONE        VARCHAR2(50),
    CONSTRAINT UQ_LOC UNIQUE (DISTRICT, SECTOR)
)
TABLESPACE water_consomation;

CREATE TABLE WATER_SECTORS (
    SECTOR_ID   NUMBER(3) PRIMARY KEY,
    SECTOR_NAME VARCHAR2(30) NOT NULL UNIQUE
)
TABLESPACE water_consomation;

CREATE TABLE WATER_METERS (
    METER_ID     NUMBER(5) PRIMARY KEY,
    LOCATION_ID  NUMBER(5) NOT NULL,
    SECTOR_ID    NUMBER(3) NOT NULL,
    METER_STATUS VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (METER_STATUS IN ('ACTIVE','INACTIVE')),
    CONSTRAINT FK_WM_LOCATION FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID),
    CONSTRAINT FK_WM_SECTOR   FOREIGN KEY (SECTOR_ID) REFERENCES WATER_SECTORS(SECTOR_ID)
)
TABLESPACE water_consomation;

CREATE TABLE WATER_CONSUMPTION (
    CONSUMPTION_ID NUMBER(7) PRIMARY KEY,
    METER_ID       NUMBER(5) NOT NULL,
    CONSUMPTION_DATE DATE NOT NULL,
    VOLUME         NUMBER(8,2) CHECK (VOLUME >= 0),
    CONSTRAINT FK_WC_METER FOREIGN KEY (METER_ID) REFERENCES WATER_METERS(METER_ID)
)
TABLESPACE water_consomation;

CREATE TABLE SYSTEM_USERS (
    USER_ID   NUMBER(5) PRIMARY KEY,
    USERNAME  VARCHAR2(30) NOT NULL UNIQUE,
    PASSWORD  VARCHAR2(20) NOT NULL,
    ROLE      VARCHAR2(20) DEFAULT 'EMPLOYEE' CHECK (ROLE IN ('ADMIN','EMPLOYEE')),
    CREATED_ON DATE DEFAULT SYSDATE
)
TABLESPACE water_consomation;



