SELECT wm.METER_ID,
       SUM(wc.VOLUME) AS TOTAL_VOLUME,
       RANK() OVER (PARTITION BY wm.SECTOR_ID ORDER BY SUM(wc.VOLUME) DESC) AS RANK_IN_SECTOR
FROM WATER_METERS wm
JOIN WATER_CONSUMPTION wc ON wm.METER_ID = wc.METER_ID
GROUP BY wm.METER_ID, wm.SECTOR_ID
ORDER BY wm.SECTOR_ID, RANK_IN_SECTOR;


SELECT wc.METER_ID,
       TO_CHAR(wc.CONSUMPTION_DATE,'YYYY-MM') AS MONTH,
       SUM(wc.VOLUME) AS MONTH_VOLUME,
       LAG(SUM(wc.VOLUME)) OVER (PARTITION BY wc.METER_ID ORDER BY TO_CHAR(wc.CONSUMPTION_DATE,'YYYY-MM')) AS PREVIOUS_MONTH
FROM WATER_CONSUMPTION wc
GROUP BY wc.METER_ID, TO_CHAR(wc.CONSUMPTION_DATE,'YYYY-MM')
ORDER BY wc.METER_ID, MONTH;
